name: tdc-conda-env 
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - anndata=0.6.22
  - biopython=1.78
  - dataclasses=0.8
  - fuzzywuzzy=0.18.0
  - huggingface_hub=0.20.3
  - mygene=3.2.2
  - numpy=1.26.4
  - openpyxl=3.0.10
  - python=3.9.13
  - pip=23.3.1
  - pandas=2.1.4
  - requests=2.31.0
  - scikit-learn=1.2.2
  - seaborn=0.12.2
  - tqdm=4.65.0
  - pip:
    - accelerate==0.33.0
    - cellxgene-census==1.15.0 
    - datasets==2.20.0
    - evaluate==0.4.2
    - gget==0.28.4
    - pydantic==2.6.3
    - gget==0.28.4
    - pydantic==2.6.3
    - gget==0.28.4
    - pydantic==2.6.3
    - pytest==8.3.2
    - rdkit==2023.9.5
    - tiledbsoma==1.11.4
    - transformers==4.43.4
    - yapf==0.40.2
    - https://pypi.tuna.tsinghua.edu.cn/packages/b0/a7/64b37abff0296753cb890f50c5a2eda1d957f64bf2dce36a3b4f99bcacf0/dgl-1.1.3-cp39-cp39-manylinux1_x86_64.whl#sha256=9dcb8ac172960851cc513409d35073f69c19d9548d04f8dc1c36cc01294bbbae
    - https://download.pytorch.org/whl/cpu/torch-2.1.2%2Bcpu-cp39-cp39-linux_x86_64.whl#sha256=10df25736edb00852eca6041941e99d13502e65773d5c6164372eaaab83d976b
    - https://download.pytorch.org/whl/cpu/torchvision-0.16.1%2Bcpu-cp39-cp39-linux_x86_64.whl#sha256=048b029410bc4c7ce87b1f2b621fd8b88249c68350ee773c3152faa088e9fcca

variables:
  KMP_DUPLICATE_LIB_OK: "TRUE"
