name: tdc-conda-env 
channels:
  - conda-forge
  - defaults
dependencies:
  - dataclasses=0.8
  - fuzzywuzzy=0.18.0
  - huggingface_hub=0.20.3
  - numpy=1.26.4
  - python=3.9.13
  - pip=23.3.1
  - pandas=2.1.4
  - requests=2.31.0
  - scikit-learn=1.3.0
  - seaborn=0.12.2
  - tqdm=4.65.0
  - pip:
    - cellxgene-census==1.10.2 
    - PyTDC==0.4.1
    - rdkit==2023.9.5
    - tiledbsoma==1.7.2
    - yapf==0.40.2
