{% set version = "0.4.2" %}

package:
  name: pytdc
  version: {{ version }}

source:
  path: ../tdc

build:
  noarch: python
  number: 0

requirements:
  host:
    - dataclasses=0.8
    - fuzzywuzzy=0.18.0
    - huggingface_hub=0.20.3
    - numpy=1.26.4
    - python=3.9.13
    - pip=23.3.1
    - pandas=2.1.4
    - requests=2.31.0
    - scikit-learn=1.3.0
    - seaborn=0.12.2
    - tqdm=4.65.0
  run:
    - python
    - pip

test:
  imports:
    - imagesize

about:
  home: https://github.com/shibukawa/imagesize_py
  license: MIT
  summary: 'Getting image size from png/jpeg/jpeg2000/gif file'
  description: |
    This module analyzes jpeg/jpeg2000/png/gif image header and
    return image size.
  dev_url: https://github.com/shibukawa/imagesize_py
  doc_url: https://pypi.python.org/pypi/imagesize
  doc_source_url: https://github.com/shibukawa/imagesize_py/blob/master/README.rst